# Read the documentation: https://symfony.com/doc/master/cmf/bundles/seo/configuration.html
cmf_seo:
    persistence:
        phpcr: null
    title: '%%content_title%% | Insert your base Title'
    description: '%%content_description%% Insert you base description here.'
    content_listener: false
# app/config/config.yml
sonata_seo:
    page:
        title: Page's default title
        metas:
            name:
                description: The default description of the page
                keywords: default, sonata, seo
