# config/packages/sonata_seo.yaml

sonata_seo:
    encoding:         UTF-8
    page:
        title:            What's On Lae
        default:          sonata.seo.page.default
        metas:
            name:
                keywords:             events, lae, lae events, happening
                description:          A calendar of events happening in and around Lae City. Past events, future events and current events all in one central location...
                robots:               index, follow

            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       What's On Lae
                'og:description':     A calendar of events happening in and around Lae City. Past events, future events and current events all in one central location...

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7

            charset:
                UTF-8:    ''

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
            #'xmlns:fb':           "http://www.facebook.com/2008/fbml"