speicher210_cloudinary:
    # url: cloudinary://my-key:my-secret@my-cloud
    url: cloudinary://326698843891691:xwdIkD8Csk1f9zcxy_QOAavWOPI@hwnrajpbq
    # The next configuration variables should be defined if they are not present in the URL
    # The URL will take precedence
    cloud_name: my-cloud
    access_identifier:
        api_key: my-key
        api_secret: my-secret
    options:
        secure: true